name: dzone-github-actions-example

on: [push]

env:
  GROUP: Test
  SERVICE_NAME: exampleapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mvn package -DskipTests
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/github-actions-example-1.0.0.jar

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mvn test

  deploy:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: albanoj2.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t albanoj2.azurecr.io/dzone-github-actions-example:${{ github.sha }} .
        docker push albanoj2.azurecr.io/dzone-github-actions-example:${{ github.sha }}     
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'dzone-github-actions-example'
        images: 'albanoj2.azurecr.io/dzone-github-actions-example:${{ github.sha }}'
    - name: Azure logout
      run: |
        az logout
